COMPONENT_ADD_INCLUDEDIRS := src
COMPONENT_SRCDIRS := src
COMPONENT_REQUIRES := ESPressio_System ESPressio_Task ESPressio_Timing ESPressio_Units

CXXFLAGS += -DESPRESSIO_THREADS
CXXFLAGS += -DESPRESSIO_THREADS_VERSION_MAJOR=3
CXXFLAGS += -DESPRESSIO_THREADS_VERSION_MINOR=1
CXXFLAGS += -DESPRESSIO_THREADS_VERSION_PATCH=7
CXXFLAGS += -DESPRESSIO_THREADS_VERSION_STRING=\"3.1.7\"
